apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:N1XQtTeGd6bGGD5HKGgddeSc,iv:sgZuZK9ZGQ9AxTxbdWivuiPPZR/Hj3SMOrx/4EhofBk=,tag:l+D7Efoeg0UzL2lRxXAFbg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:F7LCc1Y80nZSkbh27/Wh8YZY+P4E7zXKC7waFbgWeHYPi+WibS35iQ==,iv:pjDWqCeuUvp/+nRc0S/L3+XOdBAslHNeVtjAlfUMpLo=,tag:c7WsBsgtfeS37xQclUPjig==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:YGMewcgymELKoUK4KiU1G+05/PNKSVsrf3yznGKnsoCbqkq3VFtfEZ0=,iv:cvmyvRMEGfJYLgvVpCfF7oj6v0dPbjaPQ6h2BW0YxTg=,tag:YH/8PCIzX7J9YY8AymgMoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQnc4VXVuSVkxVE1mYkIv
            RXFnSGRJZlB6VkZCMHQvVzRiV3JQa2ZxeVI0CmluT1B2NE9BOUdCaWNXT2VVUTFZ
            YTkxNUdIM3FCYy9kaWZPZTMvSG9RM2sKLS0tIDI2SFFUdVFuS1hrRnVzRHFoRmgv
            S3BkRXhPUDJGS1RIM1BHcXRwb3g3NU0KjX6fOK0UJnnFgJkG1Vb6X99MCgnvd2Kl
            tmHW2Cf15nP3PBf7CKMXIAl+96+tuoNeBEEwUWEc6VahCen2huHEfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vth2pqfhwztatwtae4zseqz6u0nz87tvzr07z0rmh34qvkzsxfuskyp883
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T23:26:36Z"
    mac: ENC[AES256_GCM,data:qOJcoDAKa0KfnPRCoIZ3IvCVvnaH3UCtMwlfWzM9LM1tRUEcih+3WL3NXVaaQCdARODod80B8XSJiQ569tZEfkGfmzlp1gz/qn6fbKoEGxIGSPTdlB6dvjLOFf6gwyaUfErM/lLiE91OE/VHbF5dQpo44iAU3H91zEaEEUlEBV0=,iv:impG0CAOkaIW1m+9F2AtROXPDszk9XbY+eauzSz7dS8=,tag:eMEtO/0+WkkVf8byuwX51w==,type:str]
    version: 3.13.1
