apiVersion: v1
kind: Secret
metadata:
    name: pgdump-s3
    namespace: kubeshowcase
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:WkMJI22ljA4AyvLRujTNPX8U,iv:7Fnm8tiBC8s+VFgP9yZbQhBE1+k3h5Y5OVWfVPR+I80=,tag:Wz7mKr2jd36UoxO7J44Aqw==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:tWt0MRrcOJXV3CYhEi8AqlEBEWHRQVIEib2NyzFK5Cu36DV5sPak2A==,iv:+5EAy7ZZiscT2mc4IEuPX94PCJs2wCRti6yHOy14BtE=,tag:SONiBl9EBxFkXniliR1Btw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:8N62TMKXrBUxmqq/TxHh2tOI9yMNmTVBCFsydtDXtzZEl6lojXEIo0A=,iv:Uaj+RnvFMxfZHXrcdnuHTbTme0mpZ7f2fRk8EJSkAC0=,tag:XbP5g0xunH3C8X/Kyliw+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByakhsM01tYjFXYnFBWnNk
            T1k5blVoTWJHcXN4UHZXL2JHRXV3QTVjN1FVCkpyeDdjcFpyTEdQdUNGU3REVmVT
            OXlTaUw0V04vQ1k0Vm0wSDhQNlMySkUKLS0tIFRwQ0QvZnhRQWxyYVU3T3N0Ujlq
            dlhOU0pIdXRjbEsyWENKMFZiRG51UjgKUxUiVzHz1I1LphsZKaOYJuk2qKYk6doH
            hYPoCYp0ZFShv8jLuIAQClhirnym6CBlL5uLr7YEVUq245gTOu/pIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vth2pqfhwztatwtae4zseqz6u0nz87tvzr07z0rmh34qvkzsxfuskyp883
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T23:35:11Z"
    mac: ENC[AES256_GCM,data:T2H87jVOkGvZaqTXdXPS66kcAlVKatR3oLFQWLtqcIiw7oAKwTTe9sRI8PrFdml+n4v7ZzfuywYWEs8/K3CGn016sQnc53eL4Lp6SpLmZwLXLNMcSvdsfwA6xE/odMm4an+y+xMXRyaSeDGnw+GKhN84z6Rs/f+8kx4LL9abDno=,iv:/N45f9Vq6rM8GXU2wR7dMvc+XkfMzxw/fRtEAxjbCls=,tag:kiYdwPFE++Aoxp7Qu95jIQ==,type:str]
    version: 3.13.1
