apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubeshowcase-quota
  namespace: kubeshowcase
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "8"
    requests.storage: 30Gi
    pods: "40"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kubeshowcase-limits
  namespace: kubeshowcase
spec:
  limits:
    - type: Container
      default: # applied when a container omits limits
        cpu: 500m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "2"
        memory: 1Gi
