apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: kubeshowcase-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cnpg-minio.sops.yaml
  - sops-demo.sops.yaml
  - pgdump-s3.sops.yaml
