machine:
  network:
    hostname: worker-2
    interfaces:
      - deviceSelector:
          physical: true
        dhcp: false
        addresses: [192.168.1.24/24]
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1

  nodeLabels:
    topology.kubernetes.io/region: homelab
    topology.kubernetes.io/zone: nahida
---
apiVersion: v1alpha1
kind: HostnameConfig
$patch: delete
