machine:
  network:
    hostname: worker-1
    interfaces:
      - deviceSelector:
          physical: true
        dhcp: false
        addresses: [192.168.1.23/24]
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.254

  nodeLabels:
    topology.kubernetes.io/region: homelab
    topology.kubernetes.io/zone: aether
---
apiVersion: v1alpha1
kind: HostnameConfig
$patch: delete
